# Generated by Django 4.2.5 on 2023-12-21 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_mobile_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "termsandconditions",
                    models.BooleanField(default=False, verbose_name="Agreement Signed"),
                ),
                (
                    "termspage",
                    models.URLField(
                        blank=True, null=True, verbose_name="Terms and Condition's "
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
