# Generated by Django 4.2.5 on 2024-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_usersagreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersagreement",
            name="termspage",
            field=models.URLField(
                blank=True,
                default="https://famousbusiness.in/about/Terms-Condition",
                null=True,
                verbose_name="Terms and Condition's ",
            ),
        ),
    ]
