# Generated by Django 4.2.5 on 2024-01-08 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "Listings",
            "0069_remove_premiumplan_plan_remove_userpremiumplan_plan_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandBusinessPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=1000, unique=True)),
                (
                    "business_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                (
                    "GSTN",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "CIN_No",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "DIN",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "RoC",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="RoC"
                    ),
                ),
                (
                    "company_No",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Company Number",
                    ),
                ),
                ("director", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="About us"),
                ),
                ("web_url", models.URLField(blank=True, null=True)),
                (
                    "turn_over",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Annual Turn Over",
                    ),
                ),
                (
                    "employee_count",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Total Number of Employee",
                    ),
                ),
                ("verified", models.BooleanField(blank=True, default=False, null=True)),
                ("trusted", models.BooleanField(blank=True, default=False, null=True)),
                ("trending", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "authorized",
                    models.BooleanField(
                        default=False, verbose_name="Authorized Dealer"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Search Keywords"
                    ),
                ),
                (
                    "establishment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999),
                            django.core.validators.MinValueValidator(1000),
                        ],
                        verbose_name="Establishment Year",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nature of Business",
                    ),
                ),
                (
                    "service",
                    models.TextField(
                        blank=True, null=True, verbose_name="Product & Service"
                    ),
                ),
                (
                    "icons",
                    models.FileField(
                        default="Brand_Pics/brand_icon.jpg",
                        upload_to="Brand_Pics",
                        verbose_name="Brand Icons",
                    ),
                ),
                (
                    "industry_leader",
                    models.BooleanField(default=False, verbose_name="Industry Leader"),
                ),
                (
                    "sponsor",
                    models.BooleanField(default=False, verbose_name="Sponsor Listings"),
                ),
                (
                    "super",
                    models.BooleanField(default=False, verbose_name="Super Seller"),
                ),
                (
                    "premium",
                    models.BooleanField(default=False, verbose_name="Premium Seller"),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Opening Time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Closing Time"
                    ),
                ),
                ("category", models.ManyToManyField(to="Listings.category")),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["brand_name"],
            },
        ),
        migrations.CreateModel(
            name="BrandProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Product Name")),
                (
                    "price",
                    models.CharField(max_length=15, verbose_name="Product Price"),
                ),
                (
                    "image",
                    models.FileField(
                        default="Brand_Products.default.jpg", upload_to="Brand_Products"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("trending", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Brands.brandbusinesspage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="brand_banner.jpg",
                        upload_to="Brand_Banners",
                        verbose_name="Brand Banner",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Brands.brandbusinesspage",
                    ),
                ),
            ],
        ),
    ]
