# Generated by Django 4.2.5 on 2024-01-13 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Brands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandbanner",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="brandbusinesspage",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="brandproducts",
            options={"ordering": ["-id"]},
        ),
    ]
