# Generated by Django 4.2.5 on 2023-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productandservice",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Product & Service Name"
            ),
        ),
    ]
