# Generated by Django 4.2.5 on 2023-11-24 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Listings", "0002_alter_productandservice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="employee_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of Employee"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="nature",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Nature of business"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="turn_over",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Annual turn over"
            ),
        ),
        migrations.CreateModel(
            name="BusinessPageReviewRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_date", models.DateTimeField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
                    ),
                ),
                ("review", models.TextField()),
                (
                    "business_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessPageLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.IntegerField(blank=True, null=True)),
                (
                    "business_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
