# Generated by Django 4.2.5 on 2023-11-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0003_business_employee_count_business_nature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productandservice",
            name="picture",
            field=models.FileField(
                default="Product_Service_Pic/default.png",
                upload_to="Product_Service_Pic/",
            ),
        ),
    ]
