# Generated by Django 4.2.5 on 2023-11-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0004_alter_productandservice_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesspagelike",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
