# Generated by Django 4.2.5 on 2023-11-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0005_alter_businesspagelike_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesspagereviewrating",
            name="post_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="businesspagereviewrating",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
