# Generated by Django 4.2.5 on 2023-11-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0006_alter_businesspagereviewrating_post_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="CIN_No",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="CIN No"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="DIN",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="RoC",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="RoC"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="company_No",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Company Number"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="GSTIN",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="GST No"
            ),
        ),
        migrations.CreateModel(
            name="ProductService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Product & Service Name"
                    ),
                ),
                (
                    "picture",
                    models.FileField(
                        default="product_service/default.png",
                        upload_to="product_service/",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
            ],
        ),
    ]
