# Generated by Django 4.2.5 on 2023-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0008_delete_productandservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandbusinesspage",
            name="RoC",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="RoC"
            ),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="authorized",
            field=models.BooleanField(default=False, verbose_name="Authorized Dealer"),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="closing_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Closing Time"),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="company_No",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Company Number",
            ),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="director",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="industry_leader",
            field=models.BooleanField(default=False, verbose_name="Industry Leader"),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="keywords",
            field=models.TextField(
                blank=True, null=True, verbose_name="Search Keywords"
            ),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="opening_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Opening Time"),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="Premium Seller"),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="sponsor",
            field=models.BooleanField(default=False, verbose_name="Sponsor Listings"),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="super",
            field=models.BooleanField(default=False, verbose_name="Super Seller"),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="trending",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="trusted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="brandbusinesspage",
            name="verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="industry_leader",
            field=models.BooleanField(default=False, verbose_name="Industry Leader"),
        ),
        migrations.AddField(
            model_name="business",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="Premium Seller"),
        ),
        migrations.AddField(
            model_name="business",
            name="sponsor",
            field=models.BooleanField(default=False, verbose_name="Sponsor Listings"),
        ),
        migrations.AddField(
            model_name="business",
            name="super",
            field=models.BooleanField(default=False, verbose_name="Super Seller"),
        ),
        migrations.AlterField(
            model_name="business",
            name="DIN",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="RoC",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="RoC"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="closing_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Closing Time"),
        ),
        migrations.AlterField(
            model_name="business",
            name="company_No",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Company Number",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="director",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="opening_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Opening Time"),
        ),
    ]
