# Generated by Django 4.2.5 on 2023-11-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "Listings",
            "0009_brandbusinesspage_roc_brandbusinesspage_authorized_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessEmailNumbers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=250, unique=True, verbose_name="Email ID"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
            ],
        ),
    ]
