# Generated by Django 4.2.5 on 2023-11-27 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0010_businessemailnumbers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BusinessEmailNumbers",
            new_name="BusinessEmailID",
        ),
    ]
