# Generated by Django 4.2.5 on 2023-11-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0011_rename_businessemailnumbers_businessemailid"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Product Name"
                    ),
                ),
                (
                    "price",
                    models.CharField(max_length=15, verbose_name="Product Price"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.brandbusinesspage",
                    ),
                ),
            ],
        ),
    ]
