# Generated by Django 4.2.5 on 2023-11-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0012_brandproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandproducts",
            name="image",
            field=models.FileField(
                default="Brand_Products.default.jpg", upload_to="Brand_Products"
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Product Description"
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="price",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Product Price"
            ),
        ),
    ]
