# Generated by Django 4.2.5 on 2023-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0013_brandproducts_image_productservice_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandproducts",
            name="trending",
            field=models.BooleanField(default=False),
        ),
    ]
