# Generated by Django 4.2.5 on 2023-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0015_alter_brandproducts_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="picture",
            field=models.ImageField(
                default="Business_pics/cart.png",
                upload_to="Business_pics",
                verbose_name="Profile Pic",
            ),
        ),
    ]
