# Generated by Django 4.2.5 on 2023-11-29 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0016_alter_business_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"ordering": ["id"]},
        ),
    ]
