# Generated by Django 4.2.5 on 2023-11-29 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0017_alter_business_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"ordering": ["-id"]},
        ),
    ]
