# Generated by Django 4.2.5 on 2023-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0018_alter_business_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="Footer_Images/default.jpeg", upload_to="Footer_Images"
                    ),
                ),
                (
                    "image2",
                    models.FileField(
                        blank=True,
                        default="Footer_Images/default.jpeg",
                        null=True,
                        upload_to="Footer_Images",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Image Description",
                    ),
                ),
            ],
        ),
    ]
