# Generated by Django 4.2.5 on 2023-11-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0019_footerimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                default="category_pics/B2B.svg", upload_to="category_pics"
            ),
        ),
        migrations.AlterField(
            model_name="footerimage",
            name="image",
            field=models.FileField(
                default="Footer_Images/default1.jpeg", upload_to="Footer_Images"
            ),
        ),
        migrations.AlterField(
            model_name="footerimage",
            name="image2",
            field=models.FileField(
                blank=True,
                default="Footer_Images/default.svg",
                null=True,
                upload_to="Footer_Images",
            ),
        ),
    ]
