# Generated by Django 4.2.5 on 2023-11-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0020_alter_category_image_alter_footerimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerimage",
            name="image",
            field=models.FileField(
                default="Footer_Images/default1.svg", upload_to="Footer_Images"
            ),
        ),
    ]
