# Generated by Django 4.2.5 on 2023-11-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Listings", "0021_alter_footerimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandbusinesspage",
            name="owner",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
