# Generated by Django 4.2.5 on 2023-11-30 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Listings", "0022_brandbusinesspage_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandbusinesspage",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
