# Generated by Django 4.2.5 on 2023-11-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0023_alter_brandbusinesspage_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandbusinesspage",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="brandbusinesspage",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
