# Generated by Django 4.2.5 on 2023-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0024_alter_brandbusinesspage_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="pincode",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
