# Generated by Django 4.2.5 on 2023-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0027_business_locality"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="B2B2C",
            field=models.CharField(
                blank=True,
                choices=[("B2B", "B2B"), ("B2C", "B2C")],
                max_length=5,
                null=True,
            ),
        ),
    ]
