# Generated by Django 4.2.5 on 2023-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0029_alter_brandbusinesspage_employee_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="requirement",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
