# Generated by Django 4.2.5 on 2023-12-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0030_lead_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
    ]
