# Generated by Django 4.2.5 on 2023-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0031_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_by",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
