# Generated by Django 4.2.5 on 2023-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0032_alter_lead_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="requirement",
            field=models.TextField(blank=True, null=True),
        ),
    ]
