# Generated by Django 4.2.5 on 2023-12-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0034_alter_lead_category_businesspagelead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Listings.category",
            ),
        ),
    ]
