# Generated by Django 4.2.5 on 2023-12-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0036_alter_lead_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="Business_pics/cat-img.png", upload_to="Business_pics/"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="businessimage",
            name="image",
        ),
        migrations.AddField(
            model_name="businessimage",
            name="image",
            field=models.ManyToManyField(
                to="Listings.image", verbose_name="Profile Pic"
            ),
        ),
    ]
