# Generated by Django 4.2.5 on 2023-12-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0039_alter_businessmobilenumbers_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandbusinesspage",
            name="DIN",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
