# Generated by Django 4.2.5 on 2023-12-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0041_businesspagelead_address_businesspagelead_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesspagelead",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
