# Generated by Django 4.2.5 on 2023-12-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0042_businesspagelead_price_lead_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="lead",
            name="price",
        ),
    ]
