# Generated by Django 4.2.5 on 2023-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0044_lead_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigned_benefits",
            name="assigned_lead",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
