# Generated by Django 4.2.5 on 2023-12-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0045_assigned_benefits_assigned_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPageLeadBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                ("status", models.CharField(default="Open", max_length=100)),
                ("assigned_lead", models.PositiveBigIntegerField(default=0)),
                ("viewed_lead", models.PositiveBigIntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "business_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Listings.lead",
                    ),
                ),
            ],
        ),
    ]
