# Generated by Django 4.2.5 on 2023-12-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0047_alter_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesspageleadbucket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("Expired", "Expired"),
                    ("High Priority", "High Priority"),
                    ("Viewed", "Viewed"),
                    ("Purchased", "Purchased"),
                ],
                default="Open",
                max_length=100,
            ),
        ),
    ]
