# Generated by Django 4.2.5 on 2023-12-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0049_remove_premiumplan_quantity_plandetail_benefit10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="details",
            field=models.CharField(
                blank=True, max_length=225, null=True, verbose_name="Payment Details"
            ),
        ),
    ]
