# Generated by Django 4.2.5 on 2023-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0050_order_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadbucket",
            name="viewed",
            field=models.BooleanField(default=False),
        ),
    ]
