# Generated by Django 4.2.5 on 2023-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0051_leadbucket_viewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premiumplan",
            name="price",
        ),
        migrations.AddField(
            model_name="plandetail",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Plan Price"
            ),
        ),
    ]
