# Generated by Django 4.2.5 on 2023-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0054_alter_order_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadbucket",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("Expired", "Expired"),
                    ("High Priority", "High Priority"),
                    ("Viewed", "Viewed"),
                    ("Purchased", "Purchased"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
