# Generated by Django 4.2.5 on 2023-12-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0055_leadbucket_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryWiseBusinessPageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="catagory_business_image/default.png",
                        upload_to="catagory_business_image",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.category",
                    ),
                ),
            ],
        ),
    ]
