# Generated by Django 4.2.5 on 2023-12-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0056_categorywisebusinesspageimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
