# Generated by Django 4.2.5 on 2023-12-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0057_alter_business_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryWiseBusinessSideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.FileField(
                        default="CatagoryWiseBusinessSideImages/default.png",
                        upload_to="CatagoryWiseBusinessSideImages",
                    ),
                ),
                (
                    "image2",
                    models.FileField(
                        default="CatagoryWiseBusinessSideImages/default2.png",
                        upload_to="CatagoryWiseBusinessSideImages",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.category",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CategoryWiseBusinessPageImage",
        ),
    ]
