# Generated by Django 4.2.5 on 2023-12-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0058_categorywisebusinesssideimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorywisebusinesssideimage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categywisebannersideimages",
                to="Listings.category",
            ),
        ),
    ]
