# Generated by Django 4.2.5 on 2023-12-28 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0060_jobcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="posted_by",
        ),
        migrations.DeleteModel(
            name="JOBCategory",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
