# Generated by Django 4.2.5 on 2024-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0061_remove_job_posted_by_delete_jobcategory_delete_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="plandetail",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                max_length=10,
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AddField(
            model_name="plandetail",
            name="duration_quantity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                ],
                max_length=3,
                null=True,
                verbose_name="Duration Length",
            ),
        ),
    ]
