# Generated by Django 4.2.5 on 2024-01-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0062_plandetail_duration_plandetail_duration_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpremiumplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
