# Generated by Django 4.2.5 on 2024-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0063_userpremiumplan_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpremiumplan",
            name="authorized",
            field=models.BooleanField(default=False, verbose_name="Authorized Tag"),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="industry_leader",
            field=models.BooleanField(
                default=False, verbose_name="Industry Leader Tag"
            ),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="job_post",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Job Post Quantity"
            ),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="lead_view",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Lead View Quantity"
            ),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="Premium Tag"),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="sponsor",
            field=models.BooleanField(default=False, verbose_name="Sponsor Tag"),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="super",
            field=models.BooleanField(default=False, verbose_name="Super Tag"),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="trending",
            field=models.BooleanField(default=False, verbose_name="Trending Tag"),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="trusted",
            field=models.BooleanField(default=False, verbose_name="Trusted Tag"),
        ),
        migrations.AddField(
            model_name="userpremiumplan",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Verified Tag"),
        ),
    ]
