# Generated by Django 4.2.5 on 2024-01-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0065_plancancelrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancancelrequest",
            name="approval_status",
            field=models.CharField(
                blank=True,
                choices=[("Approved", "Approved"), ("Cancelled", "Cancelled")],
                max_length=50,
                null=True,
                verbose_name="Approval Status",
            ),
        ),
    ]
