# Generated by Django 4.2.5 on 2024-01-03 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0066_alter_plancancelrequest_approval_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="authorized",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="industry_leader",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="job_post",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="lead_view",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="premium",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="sponsor",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="super",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="trending",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="trusted",
        ),
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="verified",
        ),
        migrations.AddField(
            model_name="assigned_benefits",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Plan_benefits",
                to="Listings.premiumplan",
            ),
        ),
    ]
