# Generated by Django 4.2.5 on 2024-01-04 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0067_remove_userpremiumplan_authorized_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesspageleadbucket",
            name="business_page",
        ),
        migrations.RemoveField(
            model_name="businesspageleadbucket",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="category",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="price",
        ),
        migrations.RemoveField(
            model_name="leadbucket",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="leadbucket",
            name="owner",
        ),
        migrations.DeleteModel(
            name="BusinessPageLead",
        ),
        migrations.DeleteModel(
            name="BusinessPageLeadBucket",
        ),
        migrations.DeleteModel(
            name="Lead",
        ),
        migrations.DeleteModel(
            name="LeadBucket",
        ),
        migrations.DeleteModel(
            name="LeadPrice",
        ),
    ]
