# Generated by Django 4.2.5 on 2024-01-08 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0070_remove_brandbusinesspage_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="brand",
        ),
    ]
