# Generated by Django 4.2.5 on 2024-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Brands", "0001_initial"),
        ("Listings", "0071_remove_business_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="brand",
            field=models.ManyToManyField(
                blank=True, to="Brands.brandbusinesspage", verbose_name="Brand Name"
            ),
        ),
    ]
