# Generated by Django 4.2.5 on 2024-01-08 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0072_business_brand"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
