# Generated by Django 4.2.5 on 2024-01-13 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0073_delete_banner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ads",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="assigned_benefits",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businessemailid",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businessimage",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businessmobilenumbers",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businesspagelike",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businesspagereviewrating",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="categorywisebusinesssideimage",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="clientorder",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="email",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="footerimage",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="frontcarousel",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="productservice",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="textmessage",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["-id"]},
        ),
    ]
