# Generated by Django 4.2.5 on 2024-01-20 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0074_alter_ads_options_alter_assigned_benefits_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ADS",
        ),
    ]
