# Generated by Django 4.2.5 on 2024-01-30 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Listings", "0075_delete_ads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Business Owner",
            ),
        ),
    ]
