# Generated by Django 4.2.5 on 2024-02-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0076_alter_business_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
