# Generated by Django 4.2.5 on 2024-01-20 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Listings", "0075_delete_ads"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ADImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="AD_Images/default.jpg", upload_to="AD_Images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ADPLANS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Plan Name")),
                (
                    "views_quantity",
                    models.BigIntegerField(default=0, verbose_name="Views Quantity"),
                ),
                ("price", models.CharField(default="0", verbose_name="Price")),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ADS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Almost Like New", "Almost Like New"),
                            ("Brand New", "Brand New"),
                            ("Gently used", "Gentky used"),
                            ("Heavily used", "Heavily used"),
                            ("Unboxed", "Unboxed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=False, editable=False)),
                ("verified", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Listings.category",
                    ),
                ),
                ("pictures", models.ManyToManyField(to="ADS.adimage")),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ADBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ADS.ads"
                    ),
                ),
                (
                    "ad_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ADS.adplans",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
