# Generated by Django 4.2.5 on 2024-01-20 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ADS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Amount")),
                ("order_date", models.DateTimeField(auto_now=True)),
                ("isPaid", models.BooleanField(default=False)),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Payment Details",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=50, verbose_name="Payment Status"
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(max_length=40, verbose_name="Order ID"),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=36, verbose_name="Payment ID"),
                ),
                (
                    "signature_id",
                    models.CharField(max_length=128, verbose_name="Signature ID"),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="ads",
            name="ad_id",
            field=models.CharField(
                default="ngujbjv158963", editable=False, max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ADBucket",
        ),
        migrations.AddField(
            model_name="orders",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ADS.ads",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="ad_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ADS.adplans",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
