# Generated by Django 4.2.5 on 2024-01-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ADS", "0002_orders_ads_ad_id_delete_adbucket_orders_ad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="pictures",
            field=models.ManyToManyField(blank=True, to="ADS.adimage"),
        ),
    ]
