# Generated by Django 4.2.5 on 2024-01-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ADS", "0004_alter_ads_ad_id_alter_ads_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="pictures",
        ),
        migrations.AddField(
            model_name="adimage",
            name="ad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="ADS.ads",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ads",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Active", "Active"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="ad_id",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
