# Generated by Django 4.2.5 on 2024-01-22 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ADS", "0006_adbucket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adbucket",
            old_name="views",
            new_name="assigned_view",
        ),
        migrations.AddField(
            model_name="adbucket",
            name="viewed",
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UserADView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_clicked", models.BooleanField(default=False)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ADS.ads"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
