# Generated by Django 4.2.5 on 2024-01-04 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Listings", "0068_remove_businesspageleadbucket_business_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=225, null=True)),
                ("requirement", models.TextField(blank=True, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("pincode", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Open", "Open"),
                            ("Closed", "Closed"),
                            ("Expired", "Expired"),
                            ("High Priority", "High Priority"),
                            ("Viewed", "Viewed"),
                            ("Purchased", "Purchased"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LeadBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("viewed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Open", "Open"),
                            ("Closed", "Closed"),
                            ("Expired", "Expired"),
                            ("High Priority", "High Priority"),
                            ("Viewed", "Viewed"),
                            ("Purchased", "Purchased"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lead.lead"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lead",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Lead.leadprice",
            ),
        ),
        migrations.CreateModel(
            name="BusinessPageLeadBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Closed", "Closed"),
                            ("Expired", "Expired"),
                            ("High Priority", "High Priority"),
                            ("Viewed", "Viewed"),
                            ("Purchased", "Purchased"),
                        ],
                        default="Open",
                        max_length=100,
                    ),
                ),
                ("assigned_lead", models.PositiveBigIntegerField(default=0)),
                ("viewed_lead", models.PositiveBigIntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "business_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Lead.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessPageLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=225, null=True)),
                ("requirement", models.TextField(blank=True, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("pincode", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "business_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
            ],
        ),
    ]
