# Generated by Django 4.2.5 on 2024-01-04 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Lead", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Combo Lead")),
                (
                    "benefit",
                    models.CharField(max_length=500, verbose_name="Lead Benefits"),
                ),
                ("tag_line", models.CharField(max_length=500, verbose_name="Tag Line")),
                (
                    "image",
                    models.ImageField(
                        default="Combo_Lead/default.png",
                        upload_to="Combo_Lead/",
                        verbose_name="Image",
                    ),
                ),
                ("lead_quantity", models.BigIntegerField(verbose_name="Lead Quantity")),
                ("price", models.CharField(max_length=50, verbose_name="Price")),
            ],
        ),
        migrations.CreateModel(
            name="ComboLeadBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remaining_lead",
                    models.CharField(
                        max_length=10, verbose_name="Remaining Lead Quantity"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("expired", models.BooleanField(default=False)),
                (
                    "combolead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lead.combolead"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
