# Generated by Django 4.2.5 on 2024-01-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0002_combolead_comboleadbucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comboleadbucket",
            name="remaining_lead",
            field=models.IntegerField(verbose_name="Remaining Lead Quantity"),
        ),
    ]
