# Generated by Django 4.2.5 on 2024-01-31 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0008_assignedleadperpremiumplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesspageleadbucket",
            name="status",
        ),
        migrations.RemoveField(
            model_name="leadbucket",
            name="status",
        ),
    ]
