# Generated by Django 4.2.5 on 2024-02-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0076_alter_business_owner"),
        ("Lead", "0009_remove_businesspageleadbucket_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesspagelead",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BusinessPageEnquiredLeadViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                (
                    "business_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
                (
                    "page_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Lead.businesspagelead",
                    ),
                ),
            ],
        ),
    ]
