# Generated by Django 4.2.5 on 2024-02-03 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0010_businesspagelead_views_lead_views_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadorder",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="leadorder",
            name="provider_order_id",
        ),
        migrations.RemoveField(
            model_name="leadorder",
            name="signature_id",
        ),
        migrations.AddField(
            model_name="leadorder",
            name="checksum",
            field=models.CharField(blank=True, null=True, verbose_name="Checksum"),
        ),
        migrations.AddField(
            model_name="leadorder",
            name="merchant_id",
            field=models.CharField(default="sdfdfdfdf", verbose_name="Merchant ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leadorder",
            name="provider_reference_id",
            field=models.CharField(
                default="sfdsfdfdf", max_length=40, verbose_name="Provider Reference ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leadorder",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.UUID("24ccce74-e319-4832-97ef-554677d40a8f"),
                unique=True,
                verbose_name="Transaction ID",
            ),
        ),
        migrations.AlterField(
            model_name="leadorder",
            name="amount",
            field=models.PositiveIntegerField(null=True, verbose_name="Amount"),
        ),
    ]
