# Generated by Django 4.2.5 on 2024-02-04 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0011_remove_leadorder_payment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadorder",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.UUID("d65f5988-4839-462f-8aae-11980313f557"),
                unique=True,
                verbose_name="Transaction ID",
            ),
        ),
    ]
