# Generated by Django 4.2.5 on 2024-02-04 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0012_alter_leadorder_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadorder",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.UUID("0cf52830-1535-4bbe-ad71-9ffd98f1569e"),
                verbose_name="Transaction ID",
            ),
        ),
    ]
