# Generated by Django 4.2.5 on 2024-02-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0013_alter_leadorder_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadorder",
            name="transaction_id",
            field=models.CharField(max_length=100, verbose_name="Transaction ID"),
        ),
    ]
