# Generated by Django 4.2.5 on 2024-02-05 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Lead", "0015_leadorder_merchant_order_id_leadorder_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadorder",
            name="purchased_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Purchased Date"),
        ),
        migrations.CreateModel(
            name="ComboLeadOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(max_length=100, verbose_name="Transaction ID"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(null=True, verbose_name="Amount"),
                ),
                (
                    "provider_reference_id",
                    models.CharField(
                        max_length=40, verbose_name="Provider Reference ID"
                    ),
                ),
                ("merchant_id", models.CharField(verbose_name="Merchant ID")),
                (
                    "merchant_order_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Merchant Order ID",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(blank=True, null=True, verbose_name="Checksum"),
                ),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=254, verbose_name="Payment Status"
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=255, null=True)),
                ("currency", models.CharField(default="INR", max_length=50)),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="Phonpe Message",
                        max_length=100,
                        null=True,
                        verbose_name="Phonepe Message",
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(auto_now=True, verbose_name="Purchased Date"),
                ),
                ("isPaid", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
