# Generated by Django 4.2.5 on 2024-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0016_leadorder_purchased_at_comboleadorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignedleadperpremiumplan",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businesspageenquiredleadviews",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businesspagelead",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businesspageleadbucket",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="combolead",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="comboleadbucket",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="comboleadorder",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="leadbucket",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="leadprice",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="comboleadbucket",
            name="remaining_lead",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Remaining Lead Quantity"
            ),
        ),
    ]
