# Generated by Django 4.2.5 on 2024-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0018_alter_comboleadorder_purchased_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comboleadorder",
            name="transaction_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Transaction ID"
            ),
        ),
        migrations.AlterField(
            model_name="leadorder",
            name="transaction_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Transaction ID"
            ),
        ),
    ]
