# Generated by Django 4.2.5 on 2024-02-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0077_alter_business_email"),
        ("Lead", "0020_lead_mail_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesspageleadbucket",
            name="viewed",
        ),
        migrations.CreateModel(
            name="BusinessPageLeadView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                (
                    "business_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Listings.business",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lead.lead"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
