# Generated by Django 4.2.5 on 2024-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0021_remove_businesspageleadbucket_viewed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="category_lead",
            field=models.BooleanField(
                default=False, verbose_name="Category Generated Lead"
            ),
        ),
    ]
