# Generated by Django 4.2.5 on 2024-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0023_alter_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="category_lead",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Category Generated Lead",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="expired",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="mail_sent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("Expired", "Expired"),
                    ("High Priority", "High Priority"),
                    ("Premium Quality", "Premium Quality"),
                    ("Viewed", "Viewed"),
                    ("Purchased", "Purchased"),
                    ("Completed", "Completed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="views",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
