# Generated by Django 4.2.5 on 2024-02-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lead", "0024_alter_lead_category_lead_alter_lead_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
