# Generated by Django 4.2.5 on 2024-01-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Starter", "Starter"),
                            ("Business", "Business"),
                            ("Enterprises", "Enterprises"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Page Owner", "Page Owner"),
                            ("Ads", "Ads"),
                            ("Bulk Email", "Bulk Email"),
                            ("Bulk Text Message", "Bulk Text Message"),
                            ("Bulk Messenger", "Bulk Messenger"),
                        ],
                        max_length=25,
                        verbose_name="Marketing Type",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                        max_length=10,
                        null=True,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "duration_quantity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Duration Length",
                    ),
                ),
                ("tag_line", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Plan Price"
                    ),
                ),
                (
                    "verified",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Verified Benefits",
                    ),
                ),
                (
                    "trusted",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Trusted Benefits",
                    ),
                ),
                (
                    "trending",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Trending Benefits",
                    ),
                ),
                (
                    "authorized",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Authorized Benefits",
                    ),
                ),
                (
                    "sponsor",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Sponsor Benefits",
                    ),
                ),
                (
                    "super",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Super Benefits",
                    ),
                ),
                (
                    "premium",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Premium Benefits",
                    ),
                ),
                (
                    "industry_leader",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Industry Leader Benefits",
                    ),
                ),
                (
                    "extra_benefits",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Extra Benefits",
                    ),
                ),
                (
                    "extra_benefits1",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Extra Benefits-1",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_view",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Lead View Quantity"
                    ),
                ),
                (
                    "job_post",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Job Post Quantity"
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Verified Tag"),
                ),
                (
                    "trusted",
                    models.BooleanField(default=False, verbose_name="Trusted Tag"),
                ),
                (
                    "trending",
                    models.BooleanField(default=False, verbose_name="Trending Tag"),
                ),
                (
                    "authorized",
                    models.BooleanField(default=False, verbose_name="Authorized Tag"),
                ),
                (
                    "sponsor",
                    models.BooleanField(default=False, verbose_name="Sponsor Tag"),
                ),
                ("super", models.BooleanField(default=False, verbose_name="Super Tag")),
                (
                    "premium",
                    models.BooleanField(default=False, verbose_name="Premium Tag"),
                ),
                (
                    "industry_leader",
                    models.BooleanField(
                        default=False, verbose_name="Industry Leader Tag"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PremiumPlan.plandetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPremiumPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="PremiumPlan.premiumplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanCancelRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        blank=True,
                        choices=[("Approved", "Approved"), ("Cancelled", "Cancelled")],
                        max_length=50,
                        null=True,
                        verbose_name="Approval Status",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="PremiumPlan.premiumplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
