# Generated by Django 4.2.5 on 2024-01-29 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PremiumPlan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialPlanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="PremiumPlan.premiumplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumPlanOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(verbose_name="Amount")),
                ("order_date", models.DateTimeField(auto_now=True)),
                ("isPaid", models.BooleanField(default=False)),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Payment Details",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=254, verbose_name="Payment Status"
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(max_length=40, verbose_name="Order ID"),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=36, verbose_name="Payment ID"),
                ),
                (
                    "signature_id",
                    models.CharField(max_length=128, verbose_name="Signature ID"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="PremiumPlan.premiumplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PremiumPlanBenefits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_assigned", models.PositiveBigIntegerField(default=0)),
                ("ads_allowed", models.PositiveIntegerField(default=0)),
                ("jobpost_allowed", models.PositiveIntegerField(default=0)),
                ("banner_allowed", models.PositiveBigIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Premium_Plan_benefits",
                        to="PremiumPlan.premiumplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
