# Generated by Django 4.2.5 on 2024-01-30 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0002_trialplanrequest_premiumplanorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialplanrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plandetail",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Monthly", "Monthly"),
                    ("Yearly", "Yearly"),
                    ("Daily", "Daily"),
                ],
                max_length=10,
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AlterField(
            model_name="plandetail",
            name="duration_quantity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                    ("25", "25"),
                    ("26", "26"),
                    ("27", "27"),
                    ("28", "28"),
                    ("29", "29"),
                    ("30", "30"),
                ],
                max_length=3,
                null=True,
                verbose_name="Duration Length",
            ),
        ),
        migrations.AlterField(
            model_name="trialplanrequest",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
