# Generated by Django 4.2.5 on 2024-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0003_trialplanrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialplanrequest",
            name="lead_view",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
