# Generated by Django 4.2.5 on 2024-01-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0005_premiumplanbenefits_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plandetail",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly"), ("Day", "Day")],
                max_length=10,
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AlterField(
            model_name="plandetail",
            name="name",
            field=models.CharField(
                choices=[
                    ("Trial", "Trial"),
                    ("Starter", "Starter"),
                    ("Business", "Business"),
                    ("Enterprises", "Enterprises"),
                    ("Silver", "Silver"),
                    ("Gold", "Gold"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="plandetail",
            name="type",
            field=models.CharField(
                choices=[
                    ("Trial Period", "Trial Period"),
                    ("Page Owner", "Page Owner"),
                    ("Ads", "Ads"),
                    ("Bulk Email", "Bulk Email"),
                    ("Bulk Text Message", "Bulk Text Message"),
                    ("Bulk Messenger", "Bulk Messenger"),
                ],
                max_length=25,
                verbose_name="Marketing Type",
            ),
        ),
    ]
