# Generated by Django 4.2.5 on 2024-02-06 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "PremiumPlan",
            "0006_alter_plandetail_duration_alter_plandetail_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="premiumplanbenefits",
            name="purchased_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Purchased Date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="premiumplanbenefits",
            name="banner_allowed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
