# Generated by Django 4.2.5 on 2024-02-06 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0007_premiumplanbenefits_purchased_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="provider_order_id",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="signature_id",
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="checksum",
            field=models.CharField(blank=True, null=True, verbose_name="Checksum"),
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="currency",
            field=models.CharField(default="INR", max_length=50),
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="merchant_id",
            field=models.CharField(blank=True, null=True, verbose_name="Merchant ID"),
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="merchant_order_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Merchant Order ID"
            ),
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="message",
            field=models.CharField(
                blank=True,
                default="Phonpe Message",
                max_length=100,
                null=True,
                verbose_name="Phonepe Message",
            ),
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="provider_reference_id",
            field=models.CharField(
                default="sdsds", max_length=40, verbose_name="Provider Reference ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="purchased_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Purchased Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="premiumplanorder",
            name="transaction_id",
            field=models.CharField(
                default="dffree", max_length=100, verbose_name="Transaction ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="premiumplanorder",
            name="amount",
            field=models.PositiveIntegerField(null=True, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="premiumplanorder",
            name="details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
