# Generated by Django 4.2.5 on 2024-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0008_remove_premiumplanorder_order_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumplanorder",
            name="transaction_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Transaction ID"
            ),
        ),
    ]
