# Generated by Django 4.2.5 on 2024-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0009_alter_premiumplanorder_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="premiumplanbenefits",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
