# Generated by Django 4.2.5 on 2024-09-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0010_premiumplanbenefits_expired"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonepeAutoPayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchantUserId",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Merchant User ID"
                    ),
                ),
                (
                    "MerchantSubscriptionId",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Subscription ID"
                    ),
                ),
                (
                    "subscriptionId",
                    models.CharField(
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Subscription ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount")),
                (
                    "authRequestId",
                    models.CharField(
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Auth Request ID",
                    ),
                ),
            ],
        ),
    ]
