# Generated by Django 4.2.5 on 2024-09-15 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PremiumPlan", "0012_phonepeautopayorder_premium_plan_is"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phonepeautopayorder",
            old_name="premium_plan_is",
            new_name="premium_plan_id",
        ),
    ]
