# Generated by Django 4.2.5 on 2024-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "PremiumPlan",
            "0013_rename_premium_plan_is_phonepeautopayorder_premium_plan_id",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="merchant_id",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="merchant_order_id",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="message",
        ),
        migrations.RemoveField(
            model_name="premiumplanorder",
            name="provider_reference_id",
        ),
        migrations.AddField(
            model_name="phonepeautopayorder",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
