# Generated by Django 4.2.5 on 2023-12-29 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JOB", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandjobpost",
            name="posted_by",
        ),
        migrations.RemoveField(
            model_name="businesspagejobpost",
            name="posted_by",
        ),
    ]
