# Generated by Django 4.2.5 on 2023-12-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JOB", "0002_remove_brandjobpost_posted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessjobpostactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("Selected", "Selected"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                    ("Viewed", "Viewed"),
                    ("Applied", "Applied"),
                ],
                default="Applied",
                max_length=20,
                verbose_name="Job Status",
            ),
        ),
    ]
