# Generated by Django 4.2.5 on 2024-01-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Brands", "0001_initial"),
        ("JOB", "0004_brandjobpostactivity_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandjobpost",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Brands.brandbusinesspage",
                verbose_name="Company Name",
            ),
        ),
    ]
