# Generated by Django 4.2.5 on 2024-01-09 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JOB", "0006_brandjobpost_full_time_brandjobpost_internship_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicanteducationdetails",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="applicantexperiencedetail",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="applicantskillset",
            name="applicant",
        ),
    ]
