# Generated by Django 4.2.5 on 2024-01-10 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JOB", "0009_alter_applicanteducationdetails_applicant_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicanteducationdetails",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="applicantexperiencedetail",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="applicantskillset",
            options={"ordering": ["-id"]},
        ),
    ]
