# Generated by Django 4.2.5 on 2024-01-10 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("JOB", "0011_alter_jobseekerprofile_current_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="applicant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
