# Generated by Django 4.2.5 on 2024-01-12 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JOB", "0013_applicantresume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandjobpost",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="brandjobpostactivity",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businessjobpostactivity",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="businesspagejobpost",
            options={"ordering": ["-id"]},
        ),
    ]
