# Generated by Django 4.2.5 on 2024-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JOB", "0014_alter_brandjobpost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicanteducationdetails",
            name="end_year",
            field=models.CharField(max_length=5, verbose_name="End Year"),
        ),
        migrations.AlterField(
            model_name="applicanteducationdetails",
            name="start_year",
            field=models.CharField(max_length=5, verbose_name="Start Year"),
        ),
    ]
