# Generated by Django 4.2.5 on 2024-01-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JOB", "0016_alter_applicanteducationdetails_end_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Banner Name")),
                (
                    "banner",
                    models.FileField(
                        default="JobBanner/default.jpg",
                        upload_to="JobBanner/",
                        verbose_name="Banner",
                    ),
                ),
            ],
        ),
    ]
