# Generated by Django 4.2.5 on 2024-02-06 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Software", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="softwareorder",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="softwareorder",
            name="name",
        ),
        migrations.RemoveField(
            model_name="softwareorder",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="softwareorder",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="softwareorder",
            name="provider_order_id",
        ),
        migrations.RemoveField(
            model_name="softwareorder",
            name="signature_id",
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="checksum",
            field=models.CharField(blank=True, null=True, verbose_name="Checksum"),
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="currency",
            field=models.CharField(default="INR", max_length=50),
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="merchant_id",
            field=models.CharField(default="dfrkhf", verbose_name="Merchant ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="merchant_order_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Merchant Order ID"
            ),
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="message",
            field=models.CharField(
                blank=True,
                default="Phonpe Message",
                max_length=100,
                null=True,
                verbose_name="Phonepe Message",
            ),
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="provider_reference_id",
            field=models.CharField(
                default="sfsfdf", max_length=80, verbose_name="Provider Reference ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="purchased_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Purchased Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="softwareorder",
            name="transaction_id",
            field=models.CharField(
                default="kgighnkn", max_length=100, verbose_name="Transaction ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="softwareorder",
            name="amount",
            field=models.PositiveIntegerField(null=True, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="softwareorder",
            name="details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="softwareorder",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
