# Generated by Django 4.2.5 on 2024-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Software", "0002_alter_softwareorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwareorder",
            name="transaction_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Transaction ID"
            ),
        ),
    ]
